### PR TITLE
build v4.2.1

### PR DESCRIPTION
**Pull request by boldorider4**
* [Upstream project](https://github.com/rsokl/custom_inherit)
* Parent [Jira ticket](https://anaconda.atlassian.net/browse/PKG-3010) (dependency for scikit-criteria)

### CODE REVIEW

**Review by M-Waszkiewicz-Anaconda — COMMENTED** [review]
the upstream package is to be pushed to snowflake channel, shall we upload this to snowflake, too ?

**Comment by lorepirri** [comment]
> shall we upload this to snowflake, too ?

usually the dependencies are not to be uploaded to SF unless they also required them

Yes, I remember we were doing it initially, but then have seen that Serhii pushed some snowflake dependencies  also to snowflake, so now I am confused

**Comment by lorepirri** [comment]
> * [Upstream project](https://github.com/rsokl/custom_inherit)
> * Parent [Jira ticket](https://anaconda.atlassian.net/browse/PKG-3010) (dependency for scikit-criteria)

could you please create a ticket for each of the dependencies? They would belong to the SF effort, ~but the destination channel would be `defaults`.~ and since they are NEW dependencies, they would also go to the SF channel

**Review by cbouss — APPROVED** [review]

**Review by lorepirri — APPROVED** [review]
LGTM,
if you like to, add upstream tests, but probably you would need to source the package from the sources https://github.com/rsokl/custom_inherit/archive/refs/tags/v2.4.1.tar.gz

**Review by lorepirri — APPROVED** [review]
If this goes to SF, you need to add `abs.yaml` file with the right upload channel

**Pull request merged**
